apiVersion: v1
kind: Service
metadata:
  name: backend-pod-service
  namespace: kernelns
spec:
  type: NodePort
  selector:
    app: backend-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002  # Specify a NodePort in the range 30000-32767
