apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
  namespace: kernelns
  labels:
    app: backend-pod
spec:
  containers:
  - name: backend-container
    image: nginx:latest
    ports:
    - containerPort: 80
  nodeSelector:
    kubernetes.io/hostname: minikube-m02
