apiVersion: v1
kind: Service
metadata:
  name: client-app-service
  namespace: kernelns
spec:
  type: NodePort
  selector:
    app: client-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001  # NodePort in the range 30000-32767
