apiVersion: v1
kind: Service
metadata:
  name: client-app-service
  namespace: kernelns
spec:
  selector:
    app: client-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: backend-pod-service
  namespace: kernelns
spec:
  selector:
    app: backend-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
